const express = require("express");
const router = express.Router();

const achatClientRoutes = require("./achat_client/achat_client.routes");
const achatEntrepriseRoutes = require("./achat_entreprise/achat_entreprise.routes");
const activitesBanqueRoutes = require("./activites_banque/activites_banque.routes");
const activitesDepotRoutes = require("./activites_depot/activites_depot.routes");
const autorisationsRoutes = require("./autorisations/autorisations.routes");
const avanceRoutes = require("./avance/avance.routes");
const brouillardRoutes = require("./brouillard/brouillard.routes");
const clientsRoutes = require("./clients/clients.routes");
const clientsTonnagesRoutes = require("./clients_tonnages/clients_tonnages.routes");
const commandesRoutes = require("./commandes/commandes.routes");
const creancesRoutes = require("./creances/creances.routes");
const depensesRoutes = require("./depenses/depenses.routes");
const employesRoutes = require("./employes/employes.routes");
const modificationsRoutes = require("./modifications/modifications.routes");
const paiementClientRoutes = require("./paiement_client/paiement_client.routes");
const rapportsRoutes = require("./rapports/rapports.routes");
const remiseChequeClientRoutes = require("./remise_cheque_client/remise_cheque_client.routes");
const soldeCourantRoutes = require("./solde_courant/solde_courant.routes");
const stockBonCommandeRoutes = require("./stock_bon_commande/stock_bon_commande.routes");
const stockCamionRoutes = require("./stock_camion/stock_camion.routes");
const openFileRoute = require("./open_file/open_file.routes");

router.use("/", achatClientRoutes);
router.use("/", achatEntrepriseRoutes);
router.use("/", activitesBanqueRoutes);
router.use("/", activitesDepotRoutes);
router.use("/", autorisationsRoutes);
router.use("/", avanceRoutes);
router.use("/", brouillardRoutes);
router.use("/", clientsRoutes);
router.use("/", clientsTonnagesRoutes);
router.use("/", commandesRoutes);
router.use("/", creancesRoutes);
router.use("/", depensesRoutes);
router.use("/", employesRoutes);
router.use("/", modificationsRoutes);
router.use("/", paiementClientRoutes);
router.use("/", rapportsRoutes);
router.use("/", remiseChequeClientRoutes);
router.use("/", soldeCourantRoutes);
router.use("/", stockBonCommandeRoutes);
router.use("/", stockCamionRoutes);
router.use("/", openFileRoute);

module.exports = router;
